### ISSUE TITLE
Consider making utemplate imported on demand

### ISSUE THREAD

**Issue by dpgeorge** [pfalcon/picoweb#1]
For very simple, light-weight web apps (eg just parse and/or return some json) there is no need for template machinery.  There is (almost) one point where templating is used in picoweb, namely the render_template function.  If it's never called then utemplate need never be imported (and hence take up lots of RAM).  So one can just import utemplate in that funcion and save the template loader object for next time.

**Comment by pfalcon** [comment]
I'm ok with this, but any realistic user-facing app would use templates. What's the usercase here? Perhaps, JSON API backend?

**Comment by dpgeorge** [comment]
> What's the usercase here? Perhaps, JSON API backend?

Yes, exactly, as mentioned in first post above.

Other option would be "dependency injection" and to provide dummy utemplate.py module in app directory so that was loaded instead.

Reason I didn't have a PR is because I was unsure about "render_str" function and whether you wanted to keep that.

**Comment by dpgeorge** [comment]
Let me just say that I originally was going to use http.server module and CGIHTTPRequestHandler class since that's the basic functionality I needed.  But it seemed much easier to just use picoweb, which already had all features plus coroutines (instead of threads in http.server).

Maybe we could promote picoweb as the standard way of doing micro TCP servers in uPy?

Could also make a cutdown version / variant that didn't rely on uasyncio.

**Comment by pfalcon** [comment]
> Maybe we could promote picoweb as the standard way of doing micro TCP servers in uPy?

That's certainly how I see it. I didn't look into http.server, but http.client will be a pain to port (need to allow to implement stream protocol in user classes - bunch of bloat for likely the only usecase for the foreseeable future). And yep, with picoweb existing, I'm not really interested to look into http.server. (For the very minimal cases, we have example/unix/http-server.py)

**Comment by pfalcon** [comment]
> Other option would be "dependency injection" and to provide dummy utemplate.py module in app directory so that was loaded instead.

Well, one thing a web framework should have (even pico one) is ease of use, and the above is too magic.

But speaking of that, do you also suggest for picoweb to stop depending on utemplate, and let apps which use it pull it instead?

**Comment by dpgeorge** [comment]
> But speaking of that, do you also suggest for picoweb to stop depending on utemplate, and let apps which use it pull it instead?

If that's possible then it makes sense.

FYI my json server takes about 39k heap, without utemplate.

**Comment by pfalcon** [comment]
> > Maybe we could promote picoweb as the standard way of doing micro TCP servers in uPy?
> 
> That's certainly how I see it. 

Additional point: there's https://github.com/pfalcon/micropython-uaiohttpclient (please don't miss it ;-) ). It's roughly based on original aiohttp API, but again, includes only client, whereas original package has also server support. I don't plan to work on the latter, because again there's picoweb already.

**Comment by pfalcon** [comment]
render_str() is there because it's used by notes_pico, i.e. it's straightforward translation of flask API call. Ideally, it should be replaced by generator support in utemplates (i.e. any substitution var should be able to be a generator which renders string content incrementally).

**Comment by pfalcon** [comment]
Please see if https://github.com/pfalcon/picoweb/pull/2 does what you need.

**Comment by dpgeorge** [comment]
> Please see if #2 does what you need.

It does, thanks!

**Comment by pfalcon** [comment]
Merged/published.
