### ISSUE TITLE
Support for MAX-AGE in the response headers

### ISSUE THREAD

**Issue by joewez** [pfalcon/picoweb#18]
I'm not sure if this is how it should be accomplished, but I would like specific responses to be cached by the client browser if possible.  Javascript and style sheets could benefit by only having to be downloaded once.

**Comment by pfalcon** [comment]
This can be accomplished by reading the examples (as README suggests): https://github.com/pfalcon/picoweb/blob/master/example_webapp.py#L10

**Comment by joewez** [comment]
I am unable to do this using the app.sendfile() function because the "standard" header is already used.
