### ISSUE TITLE
Typo in picoweb/__init__.py

### ISSUE THREAD

**Issue by HaMF** [pfalcon/picoweb#28]
I think, dd68a0d introduced a error (typo) in line 50 of `picoweb/__init__.py`. _h_ is supposed to be named _k_ in order for the following lines to make sense afaics. (Or, of course, the other way around...)

https://github.com/pfalcon/picoweb/blob/dd68a0d6fa99d18548b60c1801cf283e8a28bf87/picoweb/__init__.py#L50
  
Edit: Pull request for your convenience :-)

**Comment by pfalcon** [comment]
Fixed.
