### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_event_loop'

### ISSUE THREAD

**Issue by thiamugb** [pfalcon/picoweb#33]
Hello dear,
I am a beginner on picoweb with esp32 I followed your tutorial https://techtutorialsx.com/2017/09/01/esp32-micropython-http-webserver-with-picoweb/.
when I compile my test file I have it as an error
"
('192.168.1.50', '255.255.255.0', '192.168.1.1', '192.168.1.1')
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "picoweb / __ init__.py", line 283, in run
AttributeError: 'module' object has no attribute 'get_event_loop'
"

I did import the lib uasyncio and pkg_resources using ftp because upip say having no module install.
Need help.
Best regards

**Comment by pfalcon** [comment]
Unfortunately, based on the information provided, it's hard to say much except generic "Apparently you made a mistake somewhere (or there was an error somewhere)." You may want to try forum http://forum.micropython.org/ , and likely will need to provide more, step-by-step information of what you did and what results you got at each step.
