### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by Lisa999** [pfalcon/picoweb#37]
git branch
* add_method
  master

git push -u origin add_method
remote: Permission to pfalcon/picoweb.git denied to Lisa999.
fatal: unable to access 'https://github.com/pfalcon/picoweb/': The requested URL returned error: 403

???

Trying to create a PR, for this in __init__.py:
                methods = []
                if len(e) > 2:
                    extra = e[2]
                    methods = extra['methods']
                    
                if path == pattern and method in methods:

For using: @app.route("/", methods=['GET'])

**Comment by lingster** [comment]
Hi, seems like you are trying to push your changes to pfalcon/master repo. You need to clone this project, create a new branch, commit and push your changes to your copy of this repo and then make a pull request. Here's a link with details of the steps involved:

https://services.github.com/on-demand/github-cli/open-pull-request-github

**Comment by pfalcon** [comment]
It's unclear what this submission is about. I'll thus close it, feel free to resubmit with clear description. Please also see https://www.chiark.greenend.org.uk/~sgtatham/bugs.html .
