### ISSUE TITLE
App.run()

### ISSUE THREAD

**Issue by DanielIbaseta** [pfalcon/picoweb#41]
Calling app.run(...) gives an error regarding a logging dependency. Looking through the code, the import of the logging library is not of any use, so it would be nice to simply remove it, as it also does not get installed with the picoweb package and gives another error if you try to use it without installing logging manually.

I found a solution giving the parameter "debug" a value of '-1' when calling the run() method, so the condition breaks and the logging is never used.

**Comment by pfalcon** [comment]
Did you read the README?

And please edit the title to correspond to the ticket content.
