### ISSUE TITLE
Failing on ENOMEM on ESP8266

### ISSUE THREAD

**Issue by iBobik** [pfalcon/picoweb#47]
I am trying to use Picoweb on ESP8266. It is failing in memory, but I am not sure it that consumption is normal.

In REPL:
```
>>> gc.collect()
>>> gc.mem_free()
11888
>>> modules.webinterface.app.run(debug=True, port=80, run_loop=True)
* Running on http://127.0.0.1:80/
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "picoweb/__init__.py", line 299, in run
  File "uasyncio/core.py", line 155, in run_forever
  File "uasyncio/core.py", line 110, in run_forever
  File "uasyncio/__init__.py", line 240, in start_server
OSError: [Errno 12] ENOMEM
```
App definition looks like:
```
import picoweb

app = picoweb.WebApp(__name__, serve_static=True)

@app.route("/")
def index(req, resp):
    yield from picoweb.start_response(resp)
    yield from resp.awrite("test")

app.run(debug=True, port=80)
```
Libraries inc. Picoweb and uasyncio are frozen on ROM, so code should not eat RAM. There is also wifi_manager and some own code around.

Is it normal Picoweb can not run when there is 11888 free memory?

**Comment by pfalcon** [comment]
11888 bytes is quite a little for high-level webapp framework, and that's total memory, who knows how much it's fragmented.

See https://github.com/pfalcon/notes-pico#deploying-on-embedded-micropython-targets for what was known to run on esp8266, but that's with clean esp8266 environment and ~40K free.

If you have "wifi_manager and some own code around" for the amount of free memory you quote, I'd suggest to put it all aside, make a fully clean environment (as supplied by official esp8266 MicroPython build) and try again.

**Comment by iBobik** [comment]
Thank you for a quick reply!

Jan Pobořil
https://honza.poboril.cz/

19. 1. 2019 v 18:25, Paul Sokolovsky <notifications@github.com>:
