### ISSUE TITLE
Does picoweb support async handlers? If so, document this

### ISSUE THREAD

**Issue by buzzware** [pfalcon/picoweb#50]
I want to do some async operations in a handler eg. call an API, process and return the result. Would picoweb support something like :

```
@app.route("/temp")
async def temp(req, resp):       # an async handler
    temp = await httpClient.get('/status')
    yield from picoweb.start_response(resp)
    yield from resp.awrite("Temperature: "+temp['temperature'])
```

If so, please add an async example. 

It seems that when a picoweb calls awrite, it is using StreamWriter from uasyncio, and the comment on the awrite method says it is a coroutine and may not return immediately, so awaiting it makes sense.
But picoweb handlers are called as generators ("yield from") but not awaited, so cannot be async ? 
The word async hardly exists in the whole repository.
Apologies if I'm missing something, I'm new to Micropython.

**Comment by buzzware** [comment]
This suggests that async handlers might work, because "In MicroPython coroutines and generators are identical" and "The await bar() syntax is equivalent to yield from bar()"
https://github.com/peterhinch/micropython-async/blob/master/UNDER_THE_HOOD.md#2-generators-and-coroutines

**Comment by pfalcon** [comment]
Please see https://www.python.org/dev/peps/pep-0492/ and Python (not even MicroPython!) documentation for answers. Short summary: "await" is a novelty, syntactic sugar for "yield from".

Picoweb is built on top of uasyncio and thus a fully async web framework. Please see existing documentation and examples for more information.

**Comment by buzzware** [comment]
Its quite complex to understand async/await, generators, async generators, uasyncio/asyncio and micropython vs python.
I don't yet fully understand how await == "yield from" or "In MicroPython coroutines and generators are identical" vs the situation in CPython. Any good references?
I tried making my handler async and it did seem to work. I'll report back if I hit any issues.
I still think an async example or documentation mention would help.
