### ISSUE TITLE
Incorrect uasyncio function call awitestr() and memory leak issues as resolved in comments.

### ISSUE THREAD

**Issue by peterschlem** [pfalcon/picoweb#60]
In __init__.py line 252 an incorrect call to a non existent function **awritestr**
    _yield from writer.awritestr(s)_
Should be 
    _yield from writer.awrite(s)_

**Comment by pfalcon** [comment]
Why do you think it's non existent?

**Comment by peterschlem** [comment]
I did not indicate that the call was non-existent, I am pointing out that it is a typo: awritestr should be awrite

See non-existent clarification in next comment below.

from Peter Schlemowitz tablet. 
 
  On Wed, Dec 11, 2019 at 1:30 PM, Paul Sokolovsky<notifications@github.com> wrote:   
Why do you think it's non existent?

**Comment by peterschlem** [comment]
To clarify **nonexistent** the stream write function _awritestr_ is not in the _uasyncio_ version 2 library.

**Comment by peterschlem** [comment]
There is a **severe memory leak**, about 8K per request. This can be resolved by adding _gc.collect()_ as the last statement in each routing function.

A _picoweb_ app can be run in a thread (esp32) but the above memory fix still applies.

**Comment by pfalcon** [comment]
Please see https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by peterschlem** [comment]
Read all my comments.
I fixed the problem by implementing the changes as stated - this is not hokum - the program failed when loading a template where 

The awritestr is not implemented in the current uasyncio library but the memory leak is a little harder to diagnose as the initializing uasyncio loop initilization appears to be only called once at startup of the picoweb server.


Peter Schlemowitz
cell: 917 817-7396
 

    On Friday, December 20, 2019, 2:46:56 PM EST, Paul Sokolovsky <notifications@github.com> wrote:  
 
 
Please see https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by pfalcon** [comment]
> non existent function awritestr

This is incorrect, it's right there: https://github.com/pfalcon/pycopy-lib/blob/master/uasyncio/uasyncio/__init__.py#L202

Please don't report multiple issues in one ticket.

All reports must follow the guidelines: https://github.com/pfalcon/picoweb#reporting-issues
