### ISSUE TITLE
Running Picoweb on micropython

### ISSUE THREAD

**Issue by JLFra** [pfalcon/picoweb#65]
Hello,
I found a solution to run Picoweb on micropython esp32 wroom 32D
Here:
https://forum.micropython.org/viewtopic.php?f=18&t=8048&start=10
But I don't understand why it's runnig only on firmware v1.11?
Thanks to help me.
Regards.
Julien

**Comment by pfalcon** [comment]
Please see Picoweb README, https://github.com/pfalcon/picoweb , for requirements to run Picoweb.

**Comment by JLFra** [comment]
Hello,

I can't see in the README what I have found for MicroPython. Why don't you want to add in the readme. And why it don"t run only under V.1.1 firmware of micropython? Thanks to be very precise in your answer. And great for your Framework Picoweb.

**Comment by pfalcon** [comment]
Picoweb requires [Pycopy](https://github.com/pfalcon/pycopy), and this is clearly stated in the README. Working with any other Python implementations is not guaranteed, and not supported by me due to lack of resources (but see p.5 in https://github.com/pfalcon/picoweb#reporting-issues).
