### ISSUE TITLE
Is it possible to implement a 404 Error handler?

### ISSUE THREAD

**Issue by TheGreyDiamond** [pfalcon/picoweb#71]
Hello, I was wondering if there is a way to handle 404 errors.

**Comment by LoPromise** [comment]
Hi this will send a [http Statuscode](https://developer.mozilla.org/de/docs/Web/HTTP/Status) 
```
yield from picoweb.http_error(resp, "404")
yield from resp.awrite("Custom Error Message")
```

**Comment by pfalcon** [comment]
There's definitely a way to handle 404 errors. One obvious way would be to add a catch-all rule at the end of all webapp's routes. Just care should be taken to make this exactly the last route, e.g. add it with `webapp.add_url_rule()` immediately before `webapp.run()`.
