### ISSUE TITLE
Support for `mip`

### ISSUE THREAD

**Issue by AuHau** [pfalcon/picoweb#83]
It would be great to add `package.json` for the latest's Micropython 1.20's `mip` package manager.

https://docs.micropython.org/en/latest/reference/packages.html#writing-publishing-packages

**Comment by IamDaleon** [comment]
That sounds like an amazing idea!

**Comment by tacker66** [comment]
As this repository seems to be stalled somehow, I have added this in https://github.com/tacker66/picoweb.

**Comment by pfalcon** [comment]
Picoweb is a part of the Pycopy project, self-contained minimalist ecosystem https://pycopy.github.io/

**Comment by tacker66** [comment]
Thx! ... can it be downloaded with mip from there?
